version: "3"
services:
  postgresql:
    container_name: user_postgres
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=user_local
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=password
    volumes:
      - $HOME/docker/volumes/pgdata:/var/lib/postgresql/data